"""Build crawlable, dependency-free demo language pages. Use --check in CI."""
import argparse
import html
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BASE = "https://tangyistudio.github.io/tangyicam/"
LANGUAGES = {
    "zh-Hant": ("", "繁體中文", "zh_TW"),
    "en": ("en/", "English", "en_US"),
    "ja": ("ja/", "日本語", "ja_JP"),
    "zh-Hans": ("zh-cn/", "简体中文", "zh_CN"),
}

def outputs():
    template = (ROOT / "site/index.template.html").read_text(encoding="utf-8")
    catalogs = {lang: json.loads((ROOT / "site/locales" / (lang+".json")).read_text(encoding="utf-8")) for lang in LANGUAGES}
    expected = set(catalogs["zh-Hant"])
    for lang, messages in catalogs.items():
        assert set(messages) == expected, f"Translation keys differ: {lang}"
        assert all(isinstance(v, str) and v.strip() for v in messages.values()), f"Empty translation: {lang}"
    alternates = "".join(f'<link rel="alternate" hreflang="{lang}" href="{BASE+info[0]}">' for lang, info in LANGUAGES.items())
    alternates += f'<link rel="alternate" hreflang="x-default" href="{BASE}">'
    result = {}
    for lang, (route, name, og_locale) in LANGUAGES.items():
        prefix = "../" if route else ""
        menu = '<details class="language-menu"><summary aria-label="'+html.escape(catalogs[lang]["nav.language"], quote=True)+'">'+name+' <span aria-hidden="true">▾</span></summary><div class="language-options">'
        for other, (other_route, other_name, _) in LANGUAGES.items():
            current = ' aria-current="page"' if lang == other else ''
            menu += f'<a lang="{other}" hreflang="{other}" href="{prefix+other_route or "./"}"{current}>{other_name}</a>'
        menu += '</div></details>'
        og = f'<meta property="og:locale" content="{og_locale}">'
        og += ''.join(f'<meta property="og:locale:alternate" content="{info[2]}">' for other, info in LANGUAGES.items() if other != lang)
        values = {**catalogs[lang], "locale":lang, "url":BASE+route, "assetPrefix":prefix,
                  "languageMenu":menu, "alternates":alternates, "ogLocales":og}
        raw = {"languageMenu", "alternates", "ogLocales"}
        def substitute(match):
            key = match.group(1)
            assert key in values, f"Missing template value: {key}"
            return values[key] if key in raw else html.escape(values[key], quote=True)
        page = re.sub(r"\{\{([\w.]+)\}\}", substitute, template)
        assert "{{" not in page, f"Unexpanded template in {lang}"
        result[ROOT / "docs" / route / "index.html"] = page
    runtime = {lang:{k:v for k,v in messages.items() if k.startswith(("status.","render.","control."))} for lang,messages in catalogs.items()}
    result[ROOT / "docs/demo/messages.mjs"] = "// Generated by tools/build_demo.py; edit site/locales/*.json.\nconst messages="+json.dumps(runtime, ensure_ascii=False, indent=2)+";\nexport function getMessage(locale,key){const value=(messages[locale]||messages['zh-Hant'])[key];if(value===undefined)throw new Error('Unknown message: '+key);return value;}\n"
    sitemap = '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n'
    for route, _, _ in LANGUAGES.values():
        sitemap += f'<url><loc>{BASE+route}</loc>'
        sitemap += ''.join(f'<xhtml:link rel="alternate" hreflang="{lang}" href="{BASE+info[0]}"/>' for lang,info in LANGUAGES.items())
        sitemap += f'<xhtml:link rel="alternate" hreflang="x-default" href="{BASE}"/></url>\n'
    result[ROOT / "docs/sitemap.xml"] = sitemap + '</urlset>\n'
    return result

if __name__ == "__main__":
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated files are missing or stale")
    args=parser.parse_args()
    for path, content in outputs().items():
        if args.check:
            assert path.exists() and path.read_text(encoding="utf-8") == content, f"Run python tools/build_demo.py: {path}"
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    print("DEMO_I18N_BUILD_PASS", len(LANGUAGES), "languages")
